### ISSUE TITLE
Error running orb-tools/increment

### ISSUE THREAD

**Issue by dankelleher** [CircleCI-Public/orb-tools-orb#8] opened 2018-11-15 09:19 UTC
I’ve successfully published a dev version of an orb (civicteam/helm@dev:orbs) via circleci using the circleci/orb-tools@2.0.0 orb (publishing an orb for use in circleci via an orb on circleci is cool btw!)

However, I am getting this error when running Increment: "Error: User does not have access to publish SemVer orbs in this namespace.". I am using the same publish-token-variable for publish and increment and this is a token generated by my github admin account. I also created the namespace itself.

Is the publish-token-variable the place where circle gets the permissions from, or is this based on some other setting in the circle project such as the github ssh key? I presume if I am a github admin I should have permissions to run increment?

**Comment by dankelleher** [comment] 2018-11-16 13:20
That worked fine:

```
Debugger Logging: true
>> variables: map[name:civicteam/helm namespace:civicteam]
>> query: 
        query ($name: String!, $namespace: String) {
                orb(name: $name) {
                  id
                }
                registryNamespace(name: $namespace) {
                  id
                }
          }
          
>> result status: 200 OK
<< &{Orb:{ID:9b7eaf38-454d-4e81-a1b3-91e5f70b4641} RegistryNamespace:{ID:782898bc-5d4b-47d4-ba96-edef88769e8c}}
>> variables: map[name:civicteam/helm]
>> query: query($name: String!) {
                            orb(name: $name) {
                              versions(count: 1) {
                                    version
                              }
                            }
                      }
>> result status: 200 OK
<< &{Orb:{Versions:[]}}
>> variables: map[config:version: 2.1
description: |
  Deploy a helm chart on AWS EKS
commands:
  setup-kube:
    parameters:
      cluster:
        type: string
      namespace:
        default: default
        type: string
      chart:
        type: string
    steps:
    - run:
        name: Configure Kubernetes Client
        command: |
          aws eks update-kubeconfig --name  << parameters.cluster >>
          kubectl config set-context $(kubectl config current-context) --namespace << parameters.namespace >>
          # sanity check
          kubectl get services
    - run:
        name: Initialise Helm
        command: |
          helm init --client-only
          helm list | grep << parameters.chart >>
          # download any missing subcharts
          helm dep update
  upgrade:
    parameters:
      helmparams:
        default:
        type: string
      chart:
        type: string
    steps:
    - run:
        name: Update Cluster
        command: |
          helm upgrade << parameters.helmparams>> << parameters.chart >> . || export STATUS=$?
          # cleanup
          [ ${STATUS:-0} -eq 0 ] || helm rollback << parameters.chart >> $(helm history << parameters.chart >> | grep DEPLOYED | awk '{print $1}')
          exit ${STATUS}
executors:
  default:
    docker:
      - image: civicteam/circle-aws-kube

 orbId:9b7eaf38-454d-4e81-a1b3-91e5f70b4641 version:0.1.0]
>> query: 
                mutation($config: String!, $orbId: UUID!, $version: String!) {
                        publishOrb(
                                orbId: $orbId,
                                orbYaml: $config,
                                version: $version
                        ) {
                                orb {
                                        version
                                }
                                errors { message }
                        }
                }
        
>> result status: 200 OK
<< &{PublishOrb:{Orb:{ID: Name: Namespace: CreatedAt: Source: HighestVersion:0.1.0 Commands:map[] Jobs:map[] Executors:map[] Versions:[]} Errors:}}
Bumped civicteam/helm#9b7eaf38-454d-4e81-a1b3-91e5f70b4641 from 0.0.0 by minor to 0.1.0
.
Orb `civicteam/helm` has been incremented to `civicteam/helm@0.1.0`.
Please note that this is an open orb and is world-readable.
```

I think I may know what the reason is.

The docs say the token should be `publish-token-variable` (see: https://circleci.com/docs/2.0/creating-orbs/#orb-toolsincrement)

but the source code for orb-tools@2.0.2 says `token-variable` ( https://circleci.com/orbs/registry/orb/circleci/orb-tools#commands-increment )

I haven't tested this yet on circle. Am I right? Should I use token-variable instead?

**Comment by bradylill** [comment] 2018-11-16 16:33
@dankelleher that's likely the cause. It looks like there is a bit of a discrepancy in the naming.

The _command_ called `increment` uses `token-variable`
The _job_ called `increment` uses `publish-token-variable`

**Comment by dankelleher** [comment] 2018-11-17 16:59
Hmm. I was using the job though...

![image](https://user-images.githubusercontent.com/5008805/48663573-7e4e8500-ea92-11e8-8ada-0eb2fb4d4a7e.png)

I'll snoop around the source code a little more.

**Comment by yundt** [comment] 2018-11-18 23:37
@dankelleher in case it's still giving you trouble, maybe if you paste a part of your compiled config containing the `increment` command we can take another look? Here's how to get to the compiled config from the UI (the Configuration tab in the bottom right corner):
<img width="1214" alt="screen shot 2018-11-19 at 8 18 42" src="https://user-images.githubusercontent.com/555144/48679652-42bcd380-ebd6-11e8-8854-9c97c503e70e.png">

**Comment by yundt** [comment] 2018-11-20 02:57
@dankelleher closing for now, please let us know if you still have issues publishing orbs.

**Closed by yundt** 2018-11-20 02:57 UTC
